### ISSUE TITLE
'read_params_file: Can't open stdout

### ISSUE THREAD

**Issue by excited-tiger** [nicooprat/alfred-ocr#3]
![image](https://user-images.githubusercontent.com/44421536/50738128-b27d3100-120b-11e9-8315-bc40a281f029.jpeg)

**Comment by nicooprat** [comment]
I have no clue what's happening, sorry. I added the question on the forums: https://www.alfredforum.com/topic/12006-ocr-extract-text-from-snapshot/?do=findComment&comment=63988

`Processing output of 'output.notification' with arg 'read_params_file: Can't open stdout Tesseract Open Source OCR Engine v4.0.0 with Leptonica`

**Comment by excited-tiger** [comment]
> I have no clue what's happening, sorry. I added the question on the forums: https://www.alfredforum.com/topic/12006-ocr-extract-text-from-snapshot/?do=findComment&comment=63988
> 
> `Processing output of 'output.notification' with arg 'read_params_file: Can't open stdout Tesseract Open Source OCR Engine v4.0.0 with Leptonica`

**Comment by nicooprat** [comment]
@excited-tiger did you resolve your issue? If so, please share your solution for others ;)

**Comment by excited-tiger** [comment]
thank you  very much!
I have solved this problem in the following way。
```bash
export PATH=/usr/local/bin/:$PATH
screencapture -i /tmp/ocr_snapshot.png
tesseract -l chi_sim+eng /tmp/ocr_snapshot.png res

res=`cat res.txt`
echo $res
```
Thanks for your ideal!

**Comment by excited-tiger** [comment]
thank you very much!
I have solved this problem in the following way.

```bash
export PATH=/usr/local/bin/:$PATH
screencapture -i /tmp/ocr_snapshot.png

# tesseract -l [language type] /tmp/ocr_snapshot.png [outfiles]
tesseract -l chi_sim+eng /tmp/ocr_snapshot.png res

# set a variaables
res=`cat res.txt`

# Pass variables to the following file by outputting to the terminal file
echo $res
```
Thanks for your idea!
Forgive my  terrible English, and I can’t use the GitHub well.
