### ISSUE TITLE
Warning: Invalid resolution 0 dpi. Using 70 instead.

### ISSUE THREAD

**Issue by GJRobert** [nicooprat/alfred-ocr#7]
Hi, I have encountered this message in front of the result text:
```
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 209
```

**Comment by nicooprat** [comment]
I guess you took the screenshot from a secondary monitor with a different DPI. I’ve no clue how to solve this. The simplest is to move your app window on the main monitor and take the screenshot from here ;)

--
Nico Prat
nicooprat@gmail.com
@nicooprat

**Comment by GJRobert** [comment]
Hi,
I was using OCR workflow on my laptop, which has only one monitor though...

Should I consult with other related projects on this issue?

**Comment by nicooprat** [comment]
That’s weird, I never encountered this issue on my main monitor. Yes please post the solution here for others if you find it.

--
Nico Prat
nicooprat@gmail.com
@nicooprat

**Comment by bergmul** [comment]
I provided a pull request to solve the problem and #4.

**Comment by nicooprat** [comment]
Feel free to close the issue if the PR fixed your issue 👍

**Comment by GJRobert** [comment]
I have tried to import the latest `OCR.workflow` but Alfred reports incompatible.
My Alfred version is 3.7.1.

**Comment by nicooprat** [comment]
Damn, I'm using Alfred 4 indeed. Could you download the previous one, and change the bash script?

![image](https://user-images.githubusercontent.com/645641/95975459-80542680-0e16-11eb-8992-eba6fb07f733.png)

![image](https://user-images.githubusercontent.com/645641/95975488-8813cb00-0e16-11eb-8759-3115773dd392.png)

```sh
export PATH=/usr/local/bin/:$PATH

screencapture -i /tmp/ocr_snapshot.png

if [{query} = ""]; then
tesseract --dpi 300 /tmp/ocr_snapshot.png  stdout 2>&1
else
tesseract --dpi 300 /tmp/ocr_snapshot.png stdout  -l {query} 2>&1
fi 
```

**Comment by GJRobert** [comment]
> Damn, I'm using Alfred 4 indeed. Could you download the previous one, and change the bash script?

Alright then, changing the script directly in Alfred Preferences does the work. Working like a charm.
Thanks a million!
